services:

  frontend:
    image: yassine134/brainbox-frontend:latest
    build:
      context: ./front-angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - back-tier
    depends_on:
      - backend


  backend:
    image: yassine134/brainbox-backend:latest
    build:
      context: ./back-express
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - back-tier
    depends_on:
      - ollama


  ollama:
    image: ollama/ollama
    container_name: brainbox-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - back-tier
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


volumes:
  ollama_data:


networks:
  back-tier:
    driver: bridge